# Generated by Django 2.2 on 2020-09-26 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20200926_1823'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='about_me',
            field=models.TextField(blank=True, max_length=300, null=True, verbose_name='О себе'),
        ),
        migrations.AddField(
            model_name='profile',
            name='git_hub',
            field=models.URLField(blank=True, null=True, verbose_name='Git Hub'),
        ),
    ]
