# Generated by Django 2.2 on 2020-09-26 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_auto_20200926_1318'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('other', 'Разное'), ('food', 'Продукты питания'), ('household', 'Хоз. товары'), ('toys', 'Детские игрушки'), ('appliances', 'Бытовая техника'), ('services', 'Услуги')], default='other', max_length=200, verbose_name='Категория'),
        ),
    ]
