# Generated by Django 2.2 on 2020-09-26 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0005_auto_20200926_1739'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='mark',
            field=models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], verbose_name='Оценка'),
        ),
    ]
