# Generated by Django 2.2 on 2020-09-26 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0007_auto_20200927_0014'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='webapp/static/img', verbose_name='Товар'),
        ),
    ]
